name: Infrastructure CI/CD
on:
  push:
    branches: [ main ]  # mainブランチへのプッシュ時に実行
    paths:
      - 'terraform/**'          # terraformフォルダ配下の変更時のみ実行
      - '.github/workflows/infrastructure-destroy.yml'  # ワークフローファイルの変更時も実行
  workflow_dispatch:            # 手動トリガーも可能にする
env:
  AWS_REGION: ap-northeast-1


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug Secret Check
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "SECRET IS EMPTY!!"
            exit 1
          else
            echo "SECRET IS FOUND"
          fi
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: terraform # 実行ディレクトリを指定
        run: |
          terraform init
          terraform apply -auto-approve